### ISSUE TITLE
使用非Koishi标准的提及(@)在不同适配器上出现显示问题

### ISSUE THREAD

**Issue by yunkuangao** [araea/koishi-plugin-toutai#1]
Matrix:
<img width="650" alt="Snipaste_2024-08-02_15-29-04" src="https://github.com/user-attachments/assets/507ecbc9-86ab-4a17-9863-7af5b2020b8a">

Wechat:
<img width="1028" alt="Snipaste_2024-08-02_15-31-21" src="https://github.com/user-attachments/assets/f7a6adff-3e21-4a0d-b1e2-34326f886f7d">

在经过测试后，使用Koishi标准元素的提及可以解决:
参考文档: https://koishi.chat/zh-CN/guide/basic/element.html#%E6%8F%90%E5%8F%8A%E7%94%A8%E6%88%B7%E5%92%8C%E6%B6%88%E6%81%AF

**Comment by araea** [comment]
感谢反馈，新版本已使用 Koishi 标准元素的提及。
